apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://jellyfin.github.io/jellyfin-helm'
      chart: jellyfin
      targetRevision: 0.1.1
      helm:
        valueFiles:
          - $values/apps/media/jellyfin/values.yaml 
    - repoURL: 'https://github.com/JanikHenz/my-homelab.git'
      targetRevision: HEAD
      ref: values
  destination:
    name: homelab
    namespace: media
