apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages'
      chart: plex-media-server
      targetRevision: 1.4.0
      helm:
        valueFiles:
          - $values/apps/media/plex/values.yaml
    - repoURL: 'https://github.com/JanikHenz/my-homelab.git'
      targetRevision: HEAD
      ref: values
  destination:
    name: homelab
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
