apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/JanikHenz/my-homelab.git"
    targetRevision: HEAD
    path: kubernetes/plex
  destination:
    name: homelab
    namespace: media
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
