fullnameOverride: "plex"

image:
  repository: plexinc/pms-docker
  tag: 1.31.1.6733-bc0674160

nodeSelector:
  kubernetes.io/hostname: homeserver

runtimeClassName: nvidia

env:
  TZ: "Europe/Berlin"
  PLEX_CLAIM: "claim-WkmSx1CzJGQJ3YxNQ3M_"

persistence:
  config:
    enabled: true
    existingClaim: "plex-config-pvc"
  
  media:
    enabled: true
    existingClaim: "global-media-pvc"
    mountPath: /data

service:
  type: NodePort
  port: 32400
  nodePort: 30009
