fullnameOverride: "plex"

image:
  registry: index.docker.io
  repository: plexinc/pms-docker
  tag: "1.42.2.10156-f737b826c"
  pullPolicy: IfNotPresent

runtimeClassName: "nvidia"

pms:
  gpu:
    nvidia:
      enabled: true
      devices: "all"
      capabilities: "compute,video,utility"
  configExistingClaim: "plex-config-pvc"

service:
  type: NodePort
  nodePort: 30009

extraEnv:
  PLEX_CLAIM: "claim-Y12KmpW26GB4TR13hHLt"
  TZ: "Europe/Berlin"
  ADVERTISE_IP: "http://192.168.1.9:30009"

extraVolumes:
  - name: plex-media
    persistentVolumeClaim:
      claimName: global-media-pvc

volumeMounts:
  - name: plex-media
    mountPath: /data
    readOnly: true
