fullnameOverride: "plex"

image:
  repository: plexinc/pms-docker
  tag: 1.31.1.6733-bc0674160

nodeSelector:
  kubernetes.io/hostname: homeserver

runtimeClassName: nvidia

resources:
  limits:
    nvidia.com/gpu: 1

env:
  TZ: "Europe/Berlin"
  PLEX_CLAIM: "claim-g6yxykuE66pXeorSPatt"

persistence:
  config:
    enabled: true
    existingClaim: plex-config-pvc

# Diese beiden Blöcke müssen auf der gleichen Ebene wie 'persistence' stehen!
extraAppVolumeMounts:
  - name: plex-media
    mountPath: /data

extraVolumes:
  - name: plex-media
    persistentVolumeClaim:
      claimName: plex-media-pvc

service:
  type: NodePort
  port: 32400
  nodePort: 30009
