fullnameOverride: "plex"

image:
  repository: plexinc/pms-docker
  tag: 1.31.1.6733-bc0674160

nodeSelector:
  kubernetes.io/hostname: homeserver

runtimeClassName: nvidia

# GPU Ressourcen müssen direkt hier stehen
resources:
  limits:
    nvidia.com/gpu: 1

env:
  TZ: "Europe/Berlin"
  PLEX_CLAIM: "claim-p33Sj94SJ5obxFt3u5rL"

persistence:
  config:
    enabled: true
    existingClaim: "plex-config-pvc"

# Das Chart v1.4.0 erwartet diese exakten Keys für zusätzliche Mounts:
extraVolumes:
  - name: plex-media
    persistentVolumeClaim:
      claimName: "global-media-pvc"

extraVolumeMounts:
  - name: plex-media
    mountPath: /data

service:
  type: NodePort
  port: 32400
  nodePort: 30009
