image:
  repository: plexinc/pms-docker
  tag: latest

nodeSelector:
  kubernetes.io/hostname: homeserver

runtimeClassName: nvidia

resources:
  limits:
    nvidia.com/gpu: 1

env:
  TZ: "Europe/Berlin"
  PLEX_CLAIM: "claim-kgezMxrDMegAiYDiz7Kx"

persistence:
  config:
    claimName: plex-config-pvc
  extraAppVolumeMounts:
    - name: plex-media
      mountPath: /data
      subPath: ""
  extraVolumes:
    - name: plex-media
      persistentVolumeClaim:
        claimName: plex-media-pvc

service:
  type: NodePort
  externalPort: 32400
  nodePort: 30009
