apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-config-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/plex/config"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media-pv
spec:
  storageClassName: local-path
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/media"
