fullnameOverride: "sonarr"

image:
  repository: linuxserver/sonarr
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8989
  nodePort: 30011

env:
  TZ: "Europe/Berlin"
  PUID: 1000
  PGID: 1000

persistence:
  config:
    enabled: true
    type: pvc
    existingClaim: sonarr-config-pvc
  media:
    enabled: true
    type: pvc
    existingClaim: global-media-pvc
    mountPath: /data

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
