apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://k8s-at-home.com/charts/'
      chart: radarr
      targetRevision: 16.3.2
      helm:
        valueFiles:
          - $values/apps/media/radarr/values.yaml 
    - repoURL: 'https://github.com/JanikHenz/my-homelab.git'
      targetRevision: HEAD
      ref: values
  destination:
    name: homelab
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
