apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/JanikHenz/my-homelab.git'
    targetRevision: HEAD
    path: kubernetes/radarr
  destination:
    name: homelab
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
