apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-service
  namespace: media
spec:
  type: NodePort
  selector:
    app: qbittorrent
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
      nodePort: 30180
    - name: torrent-tcp
      port: 6881
      targetPort: 6881
      nodePort: 30881
      protocol: TCP
    - name: torrent-udp
      port: 6881
      targetPort: 6881
      nodePort: 30881
      protocol: UDP
