service:
  type: NodePort
  port: 5055
  # nodePort: 30055 

extraEnv:
  - name: TZ
    value: "Europe/Zurich"
    
  - name: JELLYFIN_SERVER
    value: "http://jellyfin-service:8096"

  - name: JELLYFIN_API_KEY
    valueFrom:
      secretKeyRef:
        name: api-key
        key: api-key

config:
  persistence:
    enabled: true
    size: 5Gi

resources:
  requests:
    cpu: 200m
    memory: 256Mi
